name: CI test

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: Run format check
        run: npm run format:check
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm test
      - name: build check
        run: npm run build:prod
